### PR TITLE
Alec - Fixed Leaderboard sorting by total wealth

### LINKED ISSUE #8: BUG: Fix Leaderboard Sort by Total Wealth
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

We have noticed that the leaderboard incorrectly ranks Farmers when sorting by total wealth, under certain conditions.

### Expected Behavior

Clicking on the "Total Wealth" table column on the leaderboard should sort the Farmers from least to greatest wealth, and clicking it again should sort from greatest to least wealth. 

### Current / Observed Behavior

When a farmer has between $0 and $1000 (non inclusive), we notice that they are inaccurately sorted on the leaderboard.
Screenshot 2024-11-14 at 5 23 57 PM

Sorting from greatest to least should have put the first 2 farmers at the very bottom of the list, instead it puts them at the top.

We see this when sorting from least to greatest:
Screenshot 2024-11-14 at 5 24 17 PM

The farmers with $100 and $199 should have been ranked at the top of the leaderboard for having the least wealth, but they do not appear until the very bottom

### Steps to Reproduce

1. https://happycows.dokku-00.cs.ucsb.edu/
2. Navigate to the Testing Commons
3. Navigate to the leaderboard
4. Sort by Total Wealth

### Discussion

The issue is probably one related to sorting "strings" vs. sorting "numbers", and will involve having to understand internal details of the OurTable component.

Recognize that the OurTable component is used in many places in the application, so you need a solution that doesn't involve putting specific special case code into that component.

### PR DESCRIPTION
**Pull request by alecsong222**
## Overview

Fixes the leaderboard sorting by total wealth.

## Screenshots (Optional)

Previously, the leaderboard would incorrectly sort by wealth, and would place any monetary value less than 1000 over/under ones greater, depending on the sort order. Screenshots of the issue are as follows:
image
image
Fixed:
image
image

## Feedback Request (Optional)

Other dependencies on the total wealth value could be broken, as the accessor now uses the raw value.

## Validation (Optional)

Navigate to https://happycows-dev-alecsong222-leaderboardsortbytotalwealth.dokku-09.cs.ucsb.edu/leaderboard/1
Join test commons
View leaderboard
Sort by ascending and descending and confirm the sort is correct

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #8

### CODE REVIEW

**Comment by alecsong222** [comment]
Need to add dokku link

**Review by TomShangguan — APPROVED** [review]
LGTM!

**Review by elijahelephant — APPROVED** [review]
Small change, looks good and and your dokku deployment looks good as well.

**Review by pconrad — DISMISSED** [review]
This is great!  But we should add a test as well that checks that this doesn't "regress" to the buggy state.

That test looks like this:

* Set up some leaderboard fixtures with various dollar values out of order
* Render them in the table 
* click the sort caret
* assert that they are now in the correct order.

You can find some code in the tests for OurTable that do some similar things.

**Review by pconrad — APPROVED** [review]
LGTM.  There should be a test, but I've factored that out into https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/issues/56

**Pull request merged**
