### PR TITLE
Hongtao - Full mutation coverage for ProfitsTable.js and CommonsCard.js

### LINKED ISSUE #65: Full mutation coverage for ProfitsTable.js and CommonsCard.js
Find stryker exceptions that you can remove by writing effective tests.

### PR DESCRIPTION
**Pull request by azhe12345**
## Overview

In this PR, I find stryker exceptions and remove it by writing effective tests.

## Screenshots (Optional)
Before tests:
621732614997_ pic
After tests:
631732620374_ pic
651732642326_ pic

## Validation (Optional)
1. Download this branch.
2. run npm test
3. run npx stryker run -m src/main/components/Commons/ProfitsTable.js
4. run npx stryker run -m src/main/components/Commons/CommonsCard.js
## Tests
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #65

### CODE REVIEW

**Review by TomShangguan — DISMISSED** [review]
Since all the tests passed. I think it's good to be merged.

**Review by pconrad — CHANGES_REQUESTED** [review]
I'm not sure I understand the need for these extra tests, since I'm not seeing any changes to the code going along with them.

I wonder if the stryker exceptions were already removed in another PR, and tests added by someone else that took care of those?

In which case, perhaps this PR isn't adding anything?

**Comment by azhe12345** [comment]
> I'm not sure I understand the need for these extra tests, since I'm not seeing any changes to the code going along with them.
> 
> I wonder if the stryker exceptions were already removed in another PR, and tests added by someone else that took care of those?
> 
> In which case, perhaps this PR isn't adding anything?

**Comment by azhe12345** [comment]
> I'm not sure I understand the need for these extra tests, since I'm not seeing any changes to the code going along with them.
> 
> I wonder if the stryker exceptions were already removed in another PR, and tests added by someone else that took care of those?
> 
> In which case, perhaps this PR isn't adding anything?

I believe in the main file, we did not fix the skyker expectation for commons cards.

**Review by pconrad — CHANGES_REQUESTED** [review]
Still not clear on why these tests are needed?

**Comment by pconrad** [comment]
Closing per slack conversation: https://ucsb-cs156-f24.slack.com/archives/C07PNFEB2EM/p1733244619414959

**Pull request closed without merging**
