### PR TITLE
Alec - Added Students Table

### LINKED ISSUE #46: SUBFEATURE: Table and Placeholders for Students

### PR DESCRIPTION
**Pull request by alecsong222**
## Overview

This PR adds the Table functionality and frontend component to Students.
https://happycows-dev-alecsong222-students.dokku-09.cs.ucsb.edu/
Branch - https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/tree/Alec-StudentsTable

## Screenshots (Optional)

image

## Feedback Request (Optional)

I would like clarification on whether the table would be visible to non-admin users - Edit, Create, and Delete buttons need to be hidden accordingly

## Validation (Optional)

Navigate to https://6736df13168fb974aceba3b7-bjnsvttfwy.chromatic.com/?path=/story/components-students-studentstable--empty
Go to the StudentsTable section
Ensure that the empty table and filled tables show properly

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #46 

## PR Checklist
- [x] Commented code removed
- [x] PR deals with only one concern
- [x] PR Title is descriptive enough
- [x] PR description details what a user/dev will notice is different
- [x] No merge conflicts
- [x] Deployed and linked with Dokku deployment
- [x] New branch updated with main
- [x] PR is linked to a branch
- [x] PR is linked to an issue/ticket
- [x] Linked issue is in "In Review" column on Kanban board
- [x] PR is tagged with the Team's tag
- [x] All test cases pass

### CODE REVIEW

**Review by TomShangguan — DISMISSED** [review]
LGTM! I checked the storybook and the table looks good and well formated.

**Comment by neil-roy** [comment]
Table on the storybook looks good!

**Review by pconrad — APPROVED** [review]
Code LGTM... will test

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
